apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdemo
  labels:
    app: k8sdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sdemo
  template:
    metadata:
      labels:
        app: k8sdemo
    spec:
      containers:
      - name: k8sdemo
        image: geoffirwinmarine/k8sdemo:latest
        ports:
        - containerPort: 80