on: push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: build container and deploy it
    steps:
      - uses: actions/checkout@master

      - name: dockerhub login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and Push container to dockerhub      
        run: |
          docker build . -t geoffirwinmarine/k8sdemo:0.0.1
          docker push geoffirwinmarine/k8sdemo:0.0.1

      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0'
        id: install 

      - uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.MYKUBECONFIG }}
          context: microk8s
        id: setcontext

      - uses: Azure/k8s-deploy@v1.3
        with:
          namespace: default
          images: 'geoffirwinmarine/k8sdemo:0.0.1
          manifests: |
            deployment.yaml 
          kubectl-version: 'v1.20.0'   
        id: deploy  
       