on: push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: build container and deploy it
    steps:
      - uses: actions/checkout@master

      - name: dockerhub login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and Push container to dockerhub      
        run: |
          docker build . -t geoffirwinmarine/k8sdemo
          docker push geoffirwinmarine/k8sdemo

      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0'
        id: install 

      - uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.MYKUBECONFIG }}
        id: setcontext

      # - uses: Azure/k8s-deploy@v1.4
      #   with:
      #     namespace: default
      #     images: 'geoffirwinmarine/k8sdemo:${{ github.sha }}'
      #     manifests: |
      #       deployment.yaml 
      #     kubectl-version: 'v1.20.0' 
      #     action: deploy  
      #   id: deploy 

      - name: deploy by hand
        run: |
          kubectl version --client 
          kubectl config current-context
       