on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: build container and deploy it
    steps:
      - uses: actions/checkout@master

      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0' # default is latest stable
        id: install 

      - uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.MYKUBECONFIG }}
          context: microk8s
        id: setcontext

      - uses: Azure/k8s-deploy@v1.3
        with:
          namespace: default
          images: 'geoffirwinmarine/k8sdemo:${{ github.sha }}'
          manifests: |
            deployment.yaml 
          kubectl-version: 'v1.20.0'   
        id: deploy  
       